### ISSUE TITLE
Error on expo start

### ISSUE THREAD

**Issue by Roplay1** [edgarssilva/cantina-ipc#2]
Error: Cannot resolve entry file: The `main` field defined in your `package.json` points to a non-existent path.

**Comment by edgarssilva** [comment]
Try deleting all `node_modules` and the `packages/client/__generated__` folder cd into the root and run `yarn`.
If a new `__generated___` folder is created it should work just fine.

**Comment by Roplay1** [comment]
go to `client` and run `expo start`
